import React,{useEffect,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import './style.css';
const KEY='zzm-live-v1';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(KEY+k))??f}catch{return f}};
const write=(k,v)=>{try{localStorage.setItem(KEY+k,JSON.stringify(v))}catch{}};
const questions=[
['工作群里突然出现“在吗”，你会？','马上回应','先观察三分钟','悄悄把手机翻面','怀疑人生'],
['下午三点最需要什么？','冰美式','安静五分钟','一场没邀请我的会议','一条可以摸的鱼'],
['电脑突然卡住了？','尝试排查','伸个懒腰','欣赏进度条','视为下班信号'],
['理想办公桌上有什么？','待办清单','柔软靠垫','迷你鱼缸','无限咖啡'],
['周五17:59你在想？','安排下周','晚饭吃什么','迅速消失','我居然活下来了']];
const profiles=[['🧊','沉稳的隐形掌舵人','SS','你掌握了职场最高技能：波澜不惊。'],['🪐','宇宙观察员','A+','看起来在开会，其实已经完成了一次星际旅行。'],['🎣','快乐探险家','S','你总能从忙碌中找到属于自己的小快乐。'],['⚡','效率闪电侠','A','你相信最好的摸鱼，是提前完成工作。']];
const fish=[['🐟','小银鱼',50],['🐠','泡泡鱼',28],['🐡','锦鲤',15],['✨','神秘金鱼',7]];
const date=()=>new Date().toLocaleDateString('sv-SE');
function App(){
 const [page,setPage]=useState('home'),[office,setOffice]=useState(false),[mobile,setMobile]=useState(false);
 const [stats,setStats]=useState(()=>read('stats',{visits:0,quiz:0,casts:0,catches:0,seconds:0,days:[],events:[]}));
 const [answers,setAnswers]=useState([]),[result,setResult]=useState(null),[phase,setPhase]=useState('ready'),[caught,setCaught]=useState(null);
 const [collection,setCollection]=useState(()=>read('fish',[])),[message,setMessage]=useState('');
 const timer=useRef(null),toastTimer=useRef(null);
 const update=fn=>setStats(old=>{const v=fn(old);write('stats',v);return v});
 useEffect(()=>{update(s=>({...s,visits:s.visits+1,days:[...new Set([...s.days,date()])],events:[...s.events,{type:'visit',date:date()}].slice(-150)}))},[]);
 useEffect(()=>{const id=setInterval(()=>{if(document.visibilityState==='visible'&&!office)update(s=>({...s,seconds:s.seconds+1}))},1000);return()=>clearInterval(id)},[office]);
 useEffect(()=>{const onKey=e=>{if(e.key==='Escape')setOffice(false);if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='x'){e.preventDefault();setOffice(v=>!v)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 useEffect(()=>()=>{clearTimeout(timer.current);clearTimeout(toastTimer.current)},[]);
 const toast=t=>{setMessage(t);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setMessage(''),2500)};
 const navigate=p=>{setPage(p);setMobile(false);window.scrollTo(0,0)};
 const answer=i=>{const a=[...answers,i];setAnswers(a);if(a.length===questions.length){const sum=a.reduce((s,n,i)=>s+(n+1)*(i+2),0);setResult(profiles[sum%profiles.length]);update(s=>({...s,quiz:s.quiz+1,events:[...s.events,{type:'quiz',date:date()}].slice(-150)}))}};
 const cast=()=>{if(phase!=='ready')return;setPhase('waiting');update(s=>({...s,casts:s.casts+1}));timer.current=setTimeout(()=>setPhase('bite'),1500+Math.random()*2200)};
 const reel=()=>{if(phase!=='bite')return;const n=Math.random()*100;let w=0;const type=fish.find(f=>(w+=f[2])>n)||fish[0];const item={icon:type[0],name:type[1],date:date(),id:Date.now()};setCaught(item);setCollection(old=>{const next=[item,...old].slice(0,60);write('fish',next);return next});setPhase('caught');update(s=>({...s,catches:s.catches+1,events:[...s.events,{type:'catch',date:date()}].slice(-150)}))};
 const share=async txt=>{try{if(navigator.share){await navigator.share({title:'正在忙.exe',text:txt,url:location.href});return}await navigator.clipboard.writeText(txt+' '+location.href);toast('分享内容已复制')}catch{toast('可以复制当前网址分享')}};
 return <div className="app">
 <header className="header"><div className="head"><button className="brand" onClick={()=>navigate('home')}>▣ 正在忙<span>.exe</span><small> BETA</small></button><nav className={mobile?'open':''}>{[['home','首页'],['quiz','人格测试'],['fish','带薪钓鱼'],['stats','摸鱼报告']].map(([id,label])=><button key={id} className={page===id?'current':''} onClick={()=>navigate(id)}>{label}</button>)}</nav><div className="actions"><button className="boss" onClick={()=>setOffice(true)}>▣ 老板来了 <small>Ctrl ⇧ X</small></button><button className="hamburger" onClick={()=>setMobile(!mobile)} aria-label="菜单">☰</button></div></div></header>
 <main className="container">
 {page==='home'&&<><section className="hero"><div><div className="eyebrow">● OFFICE MODE: SECRETLY HAPPY</div><h1>工作可以很忙，<br/><em>快乐不能拖。</em></h1><p>欢迎来到一个不太正经的办公系统。在这里，认真上班是表面功夫，偷偷快乐才是隐藏主线。</p><div className="buttons"><button className="primary" onClick={()=>navigate('quiz')}>测测我的职场人格 →</button><button className="secondary" onClick={()=>navigate('fish')}>🎣 去鱼塘放空</button></div><p className="small">✓ 无需注册　 ✓ 免费体验　 ✓ 记录仅保存在本机</p></div><div className="desktop"><div className="top">● MY DESKTOP / LIVE <span>☁ ONLINE</span></div><div className="fake-window"><div className="window-title">🔴 🟡 🟢　today_tasks.xlsx</div><div className="bars"><i/><i/><i/><i/><i/></div><div className="window-message">STATUS　假装很忙中... ✳</div></div><span className="desk-fish">🐠</span><span className="desk-coffee">☕</span></div></section><section className="stats-strip"><div>今日状态<b>☕ 工位已就绪</b></div><div>本机访问次数<b>{stats.visits}</b></div><div>累计钓鱼<b>{stats.catches} 条</b></div><div>今日心情<b>✨ 放空待机中</b></div></section><section className="section"><div className="eyebrow">YOUR SECRET TOOLBOX</div><h2>今日摸鱼装备 ↗</h2><p>工作间隙的快乐，从这里开始。</p><div className="tiles"><button className="tile lilac" onClick={()=>navigate('quiz')}><span>🪐</span><small>01 / TEST</small><h3>打工人人格测试</h3><p>五道题，找到职场隐藏属性。</p></button><button className="tile aqua" onClick={()=>navigate('fish')}><span>🐠</span><small>02 / PLAY</small><h3>带薪钓鱼</h3><p>一条鱼，换一分钟好心情。</p></button><button className="tile peach" onClick={()=>setOffice(true)}><span>📊</span><small>03 / HIDE</small><h3>一键伪装办公</h3><p>虚构报表，随时切换。</p></button><button className="tile blue" onClick={()=>navigate('stats')}><span>📈</span><small>04 / REPORT</small><h3>摸鱼绩效报告</h3><p>看看快乐积累了多少。</p></button></div></section><section className="banner"><div><h3>小声提醒：快乐不需要等下班。</h3><p>今天也允许自己休息一下。</p></div><button className="secondary" onClick={()=>share('我发现一个超有趣的摸鱼网站！')}>分享给工友 ↗</button></section></>}
 {page==='quiz'&&<section className="subpage"><div className="eyebrow">OFFICE PERSONALITY CHECK</div><h1>你的职场隐藏人格 ✳</h1><p>五道趣味题，没有标准答案。数据仅在本机计算。</p>{!result?<div className="panel quiz"><div className="progress"><span>人格识别中</span><b>{answers.length+1}/{questions.length}</b></div><div className="progressbar"><i style={{width:answers.length/questions.length*100+'%'}}/></div><div className="emoji">{['🕵️','☕','💻','🪴','🌆'][answers.length]}</div><h2>{questions[answers.length][0]}</h2><div className="choices">{questions[answers.length].slice(1).map((a,i)=><button key={a} onClick={()=>answer(i)}><b>{'ABCD'[i]}</b>{a}<span>→</span></button>)}</div></div>:<div className="panel quiz"><div className="emoji">{result[0]}</div><div className="eyebrow">摸鱼段位 {result[2]}</div><h2>{result[1]}</h2><p>{result[3]}</p><div className="buttons center"><button className="primary" onClick={()=>share('我的职场人格是'+result[1])}>分享结果 ↗</button><button className="secondary" onClick={()=>{setAnswers([]);setResult(null)}}>重新测试</button></div></div>}</section>}
 {page==='fish'&&<section className="subpage"><div className="eyebrow">PAID FISHING CLUB</div><h1>带薪钓鱼俱乐部 🎣</h1><p>有些事情急不来，比如鱼上钩。</p><div className="fish-grid"><div className="panel fishing"><div className="lake-header">☀ 摸鱼湖 · 全天营业 <span>LV.01 新晋钓手</span></div><div className="lake"><div className="sun"/><div className="hills"/><div className="water"><span>🐟</span><span>🐠</span></div><div className="rod">{phase==='bite'?'🎣 ！':'🎣'}</div></div><div className="fish-controls"><p>{phase==='ready'?'鱼塘风平浪静，试试运气。':phase==='waiting'?'安静等待，鱼儿正在靠近……':phase==='bite'?'有鱼咬钩，快收杆！':'恭喜钓到 '+caught?.icon+' '+caught?.name}</p>{phase==='ready'?<button className="primary" onClick={cast}>抛出鱼竿 🎣</button>:phase==='waiting'?<button className="primary" disabled>等待上钩…</button>:phase==='bite'?<button className="primary" onClick={reel}>收杆！ ✨</button>:<button className="primary" onClick={()=>{setPhase('ready');setCaught(null)}}>再钓一条 ↻</button>}</div></div><aside><div className="panel aside"><h3>🏆 我的战绩</h3><div className="big-number">{stats.catches} <small>条</small></div><p>累计鱼获</p><hr/><p>抛竿 {stats.casts} 次　|　品种 {new Set(collection.map(f=>f.name)).size}/4</p></div><div className="panel aside"><h3>🐠 最近收获</h3>{collection.length?collection.slice(0,6).map(f=><div className="catch" key={f.id}>{f.icon} {f.name}<small>{f.date}</small></div>):<p>鱼篓还是空的，去试试吧。</p>}</div></aside></div></section>}
 {page==='stats'&&<section className="subpage"><div className="eyebrow">PERSONAL HAPPINESS ANALYTICS</div><h1>我的摸鱼绩效报告 📈</h1><p>只统计当前浏览器，不是网站全站数据。</p><div className="tiles stat-tiles">{[['⏱','累计停留',Math.floor(stats.seconds/60)+'分钟'],['🐟','累计鱼获',stats.catches+'条'],['🪐','人格测试',stats.quiz+'次'],['📅','访问天数',stats.days.length+'天']].map(([icon,label,val])=><div className="panel metric" key={label}><span>{icon}</span><p>{label}</p><b>{val}</b></div>)}</div><div className="panel report"><h2>今日放空观察报告</h2><p>认真工作，也要认真休息。</p><div className="report-highlight">✳ {stats.catches>4?'深海摸鱼专家':stats.quiz>0?'办公室探险者':'快乐探索新人'}</div><button className="primary" onClick={()=>share('我的摸鱼报告：钓鱼'+stats.catches+'条，完成人格测试'+stats.quiz+'次。')}>分享摸鱼报告 ↗</button><p className="fine">隐私说明：访问次数、停留时间、游戏次数和鱼获仅保存在浏览器 localStorage。删除浏览器数据后会丢失。本站不包含后台分析服务。</p></div></section>}
 </main><footer><div className="container"><b>正在忙<span>.exe</span></b><p>一个不太正经，但认真做快乐的网站。 © 2026</p></div></footer>
 {message&&<div className="toast">{message}</div>}
 {office&&<div className="office" role="dialog" aria-modal="true" aria-label="虚构办公报表"><div className="office-head"><b>🟩 运营汇总_季度分析.xlsx</b><button onClick={()=>setOffice(false)}>退出伪装 ✕</button></div><div className="office-nav">文件　 开始　 插入　 页面布局　 公式　 数据　 审阅　 视图</div><div className="office-ribbon">▤ 粘贴　　　 Ｂ　Ｉ　Ｕ　　　 ▥ 对齐方式　　　 ￥　% 数字格式　　　 ▩ 条件格式</div><div className="formula">A1　 ƒx　 2026 年度业务运营汇总（演示虚构数据）</div><div className="sheet-wrap"><table className="sheet"><thead><tr>{['','A','B','C','D','E','F','G'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{Array.from({length:34},(_,i)=><tr key={i}><th>{i+1}</th>{(i===0?['业务部门','一季度','二季度','三季度','四季度','年度合计','状态']:i===1?['华东区域','125,800','133,600','141,200','152,900','553,500','已复核']:i===2?['华南区域','98,500','110,200','118,800','127,300','454,800','已复核']:i===3?['华北区域','89,300','93,700','102,600','115,100','400,700','已复核']:i===4?['西南区域','65,200','72,900','79,100','87,600','304,800','已复核']:i===5?['年度汇总','378,800','410,400','442,700','481,900','1,713,800','完成']:['','','','','','','']).map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div><div className="office-footer">工作表1　 工作表2　+ <span>虚构演示数据 · Esc 或 Ctrl+Shift+X 返回</span></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
